### ISSUE TITLE
Info on project

### ISSUE THREAD

**Issue by docop** [BrunoBBS/ArduinoJoystickFirmware#1]
Hi it look quite a great project. I'm not that good at coding.. Do you plan to put some more detail on how to used it or operate ? like a readmi with picture or so.. 
Thanks in advance

**Comment by BrunoBBS** [comment]
Hi @docop, I didn't think there would be anyone interested in this project and I was postponing making the documentation. I think I can work out a readme and some comments in the code by the end of the weekend.

**Comment by BrunoBBS** [comment]
Hello @docop, I added some documentation to the project. If you are satisfied with it, you are free to close this issue. Otherwise, just ask.

**Comment by docop** [comment]
Wow, very nice. But no, indeed, quite usefull. Thanks for the details !
